apiVersion: v1
kind: Service
metadata:
  name: greeting-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: greeting-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-api
spec:
  selector:
    matchLabels:
      app: greeting-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greeting-api
    spec:
      containers:
        - image: wildmouse/greeting_api:latest
          name: greeting-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: greeting-api
