apiVersion: batch/v1
kind: Job
metadata:
  name: batch
spec:
  template:
    spec:
      containers:
        - name: batch
          image: wildmouse/greeting_batch
      restartPolicy: Never
  completions: 5
  parallelism: 3
  backoffLimit: 10